In [2]:
# %load write_mat.py
##
#   load .mat files and write the contens to a 
#   .mat file.
#    the files has two fields - 'inputs' and 'targets'  
#   'inputs' is a numpy array of tuples
#   'targets' is from 0 to 7 (for grid 'A' to 'H')

import scipy.io
import numpy as np
import os.path
import re

inputs = []
targets = []

def init():
    inputs = []
    targets = []

def loadMat(file):
    '''
     load matfile named 'file' ..
    '''
    return scipy.io.loadmat(file)

def load_local_features(data,target_value):
    ''' load local features from data '''
    feature_name = []

    # extract the local feature name
    for i in data:
        if not re.match(r'__*',i) and i!='F' :
            if not re.match(r'global*',i): # skipping global feature
                if not re.match(r'wav_var',i) : 
                #if re.match(r'mean',i) or re.match(r'diff',i) or re.match(r'range',i):
                    feature_name.append(i)
    input  = zip( *[ data[i][0] for i in feature_name ])

    target =  [[target_value] for i in xrange(len(input))] 

    inputs.extend(input)
    targets.extend(target)

def write_to_file(filename):
    '''
        write inputs and targets to a filename .mat file
     '''
    #np.savez(filename,inputs,targets)
    scipy.io.savemat(filename, mdict = {'inputs':inputs,'targets':targets} )



def main():
    grids = ['A','B','C','D','E','F','G','H'];
    init()

    for grid in grids:
        #filename = '../feature_data/matfile/{0}/{0}_P{1}.mat'\
        #.format(grid,i)
        filename = '../mat/me/features/Grid{0}.mat'\
            .format(grid)
        if os.path.exists(filename):
            load_local_features(
                loadMat(filename), ord(grid)-ord('A')
            )
    file_to_save = 'feature_data/features.mat'
    write_to_file(file_to_save)

if __name__ == '__main__':
    main()






 

In [3]:
main()

In [8]:
# %load svm_1.py
from __future__ import division
import scipy.io
import numpy as np
import scipy as sp
import sys
import random
from sklearn import svm

allf = scipy.io.loadmat('feature_data/features.mat')
inputs = allf['inputs']
targets = allf['targets']

assert len(inputs)==len(targets)
percent = 0.75 # default 75% train data

#if len(sys.argv)>1:
#    percent = float(sys.argv[1])

z = zip(inputs,targets)
random.shuffle(z)

train_last_index = int( percent * len(z) )

# train inputs
X = np.array([ z[i][0] for i in xrange(train_last_index) ])
Y = np.array([ int(z[i][1]) for i in xrange(train_last_index) ])

assert len(X)==len(Y)

clf = svm.SVC()
clf.fit(X,Y)

test_x = np.array([ z[i][0] for i in xrange( train_last_index,len(z) )  ])
test_y = np.array([ int(z[i][1]) for i in xrange(train_last_index,len(z)) ])

pr = clf.predict(test_x)

d = abs(pr-test_y)

s = sum([1  for i in d if i!=0])

print 'Error percent :',s/len(d)*100



Error percent : 23.1366459627


In [18]:
%run svm_1.py

Error percent : 21.5838509317


In [19]:
allf['inputs'][0]

array([ -6.24545679,  -0.7109509 ,  -5.4403286 ,  60.02294948,
        60.02294948, -13.88056216])

In [20]:
%run write_mat.py

In [26]:
%run svm_1.py

Error percent : 28.2608695652


In [24]:
allf['inputs']

array([[ -6.24545679,  -0.7109509 ,  -5.4403286 , ...,  60.02294948,
        -13.88056216, -62.35149755],
       [ -6.36115672,  -0.57511224,  -5.60568865, ...,  60.02297139,
        -13.92614652, -61.54056734],
       [ -6.50407888,  -0.63179481,  -5.92923723, ...,  60.02243203,
        -14.52637645, -62.35149755],
       ..., 
       [ -4.53467648,  -1.65715016,  -2.21450199, ...,  50.04282168,
         -6.42760601, -65.12408627],
       [ -4.51716009,  -1.73587005,  -2.80303806, ...,  49.98749974,
         -8.04276505, -63.73779191],
       [ -4.94758398,  -1.38298702,  -3.09736442, ...,  49.92780845,
         -8.69964734, -62.35149755]])

In [27]:
allf['inputs'][0]

array([ -6.24545679e+00,  -7.10950898e-01,  -5.44032860e+00,
         6.00229495e+01,   6.00229495e+01,  -1.38805622e+01,
         8.33851424e-28])

In [30]:
%run svm_1.py

Error percent : 34.4720496894


In [31]:
allf['inputs'][0]

array([ -3.38813179e-21,   2.83540091e-03,  -7.10950898e-01,
        -5.44032860e+00,   6.00229495e+01,  -1.38805622e+01,
         3.38813179e-21,   0.00000000e+00,   6.77626358e-21])

In [34]:
re.match(r'd\d','d1')

In [35]:
%run write_mat.py

In [36]:
%run svm_1.py

Error percent : 24.8447204969


In [37]:
allf['inputs'][0]

array([ -6.24545679,  -0.7109509 ,  -5.4403286 ,  60.02294948, -13.88056216])